Switch a number of upstream locations away from ssw; some tweaks to Linux build

diff --git a/deploy/clean-build-and-package b/deploy/clean-build-and-package
--- a/deploy/clean-build-and-package
+++ b/deploy/clean-build-and-package
@@ -2,11 +2,9 @@
 
 set -eu
 
-current=$(hg id | awk '{ print $1; }')
-
-case "$current" in
-    *+) echo "ERROR: Current working copy has been modified - not proceeding";exit 2;;
-    *);;
+case $(git status --porcelain --untracked-files=no) in
+    "") ;;
+    *) echo "ERROR: Current working copy has been modified - not proceeding"; exit 2;;
 esac
 
 version=`perl -p -e 's/^[^"]*"([^"]*)".*$/$1/' version.h`
@@ -27,6 +25,8 @@ if [ -d /Applications ]; then
 else
 
     ./deploy/linux/build-and-test.sh
+
+    current=$(git rev-parse --short HEAD)
 
     squashedversion=$(echo "$version" | sed 's/_-//g')
 
